#configuration for dataset
data:
  datasetname: Human
  pair_path: Data/Human/human.txt
  aac_path: Data/Human/human_aac.npz
  dipeptide_path: Data/Human/human_dipeptide.npz
  graph_emb_path: Data/Human/graph_emb.npz
  text_emb_dir: Data/Human/Ks-coding-esmc/
  network_path: Data/Human/nw.txt

# training configuration
train:
  epoch: 30
  batchsize: 32
  lr: 0.001
  patience: 5
  contrastive_loss_coef: 1.0
  seed: 123

# model configuration 960 1920 2880 3840 4800
model:
  embed_hid_dim: 128
  embedding_size: 3840
  dropout: 0.2

# evaluation configuration
output:
  rst_file: ./results/human3/results.tsv
  model_save_dir: ./results/human3
