# configuration for dataset
data:
  datasetname: PIPR-cut
  pair_path: Data/PIPR-cut/PIPR_cut_2039.txt
  aac_path: Data/PIPR-cut/PIPR_cut_aac.npz
  dipeptide_path: Data/PIPR-cut/PIPR_cut_dipeptide.npz
  graph_emb_path: Data/PIPR-cut/graph_emb.npz
  text_emb_dir: Data/PIPR-cut/Ks-coding-esmc/
  network_path: Data/PIPR-cut/nw.txt

# training configuration
train:
  epoch: 30
  batchsize: 32
  lr: 0.001
  patience: 5
  contrastive_loss_coef: 1.0
  seed: 123

# model configuration
model:
  embed_hid_dim: 128
  embedding_size: 3840
  dropout: 0.2

# evaluation configuration
output:
  rst_file: ./results/pipr-1.0/results.tsv
  model_save_dir: ./results/pipr-1.0
