# 数据相关配置
data:
  datasetname: Yeast
  pair_path: Data/Yeast/protein.actions.tsv
  aac_path: Data/Yeast/yeast_aac.npz
  dipeptide_path: Data/Yeast/yeast_dipeptide.npz
  graph_emb_path: Data/Yeast/graph_emb.npz
  text_emb_dir: Data/Yeast/Ks-coding-esmc/
  network_path: Data/Yeast/nw.txt

# 训练相关配置
train:
  epoch: 30
  batchsize: 32
  lr: 0.001
  patience: 5
  contrastive_loss_coef: 1.0
  seed: 123

# 模型相关配置
model:
  embed_hid_dim: 128
  embedding_size: 3840
  dropout: 0.2

# 输出相关配置
output:
  rst_file: ./results/yeast/results.tsv
  model_save_dir: ./results/yeast
